import GuardLayoutWrapper from '@/hocs/GuardLayoutWrapper';
import LayoutPublic from '@/views/layouts/LayoutPublic/LayoutPublic';
import ContactPage from '@/views/pages/contact';
import { Metadata } from 'next';
import { ReactElement } from 'react';

export const metadata: Metadata = {
  title: 'Contact - FastE',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <GuardLayoutWrapper
      getLayout={(page: ReactElement) => <LayoutPublic>{page}</LayoutPublic>}
      authGuard={false}
      guestGuard={false}
    >
      <ContactPage />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'FAQPage',
            mainEntity: [
              {
                '@type': 'Question',
                name: 'How can I contact FastE?',
                acceptedAnswer: {
                  '@type': 'Answer',
                  text: 'You can contact FastE via the contact form.',
                },
              },
            ],
          }),
        }}
      />
    </GuardLayoutWrapper>
  );
}
