'use client';

import GuardLayoutWrapper from '@/hocs/GuardLayoutWrapper';
import LayoutSeller from '@/views/layouts/LayoutSeller';
import { ReactElement, useEffect, useState } from 'react';
import { getDetailShopMe } from '@/services/shop';
import { useRouter } from 'next/navigation';
import { ROUTE_CONFIG } from '@/configs/router';
import { LoadingDialog } from '@/components/loading/LoadingDialog';

// export const metadata: Metadata = {
//   title: 'Seller Center - FastE',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoading, setIsLoading] = useState(false);
  const router = useRouter();
  const fetchShopMe = async () => {
    setIsLoading(true);

    try {
      const res = await getDetailShopMe();

      if (res.error && res.status === 'error') {
        return router.replace('/seller/register');
      }
    } catch (error) {
      console.error(error);
    }

    setIsLoading(false);
  };
  useEffect(() => {
    fetchShopMe();
  }, []);

  if(isLoading) {
    return <LoadingDialog isLoading={true} />
  }
  return (
    <GuardLayoutWrapper
      getLayout={(page: ReactElement) => <LayoutSeller>{page}</LayoutSeller>}
      authGuard={true}
    >
      {children}
    </GuardLayoutWrapper>
  );
}
