import type { Metadata } from 'next';
import GuardLayoutWrapper from '@/hocs/GuardLayoutWrapper';
import LayoutSeller from '@/views/layouts/LayoutSeller';
import { ReactElement } from 'react';

export const metadata: Metadata = {
  title: 'Seller Center - FastE',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GuardLayoutWrapper
      getLayout={(page: ReactElement) => <LayoutSeller>{page}</LayoutSeller>}
      authGuard={true}
    >
      {children}
    </GuardLayoutWrapper>
  );
}
