import GuardLayoutWrapper from '@/hocs/GuardLayoutWrapper';
import LayoutPublic from '@/views/layouts/LayoutPublic/LayoutPublic';
import ContactPage from '@/views/pages/contact';
import { ProductListPage } from '@/views/pages/product';
import { Metadata } from 'next';
import { ReactElement, Suspense } from 'react';
import { LoadingSpinner } from '@/components/loading/LoadingSpinner';

export const metadata: Metadata = {
  title: 'List product - FastE',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <GuardLayoutWrapper
      getLayout={(page: ReactElement) => <LayoutPublic>{page}</LayoutPublic>}
      authGuard={false}
      guestGuard={false}
    >
      <Suspense fallback={<LoadingSpinner />}>
        <ProductListPage />
      </Suspense>
    </GuardLayoutWrapper>
  );
}
