import CreateProductPage from '../../../../../views/pages/sellercenter/products/create';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Thêm sản phẩm - FastE',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <CreateProductPage />
    </>
  );
}
